/**
 * TypeScript bindings for the Calendry solver gRPC contract.
 *
 * Generated from the .proto files in this repository — see scripts/generate.sh.
 * Do not edit the contents of src/generated by hand; it is a build artifact and
 * is not committed.
 */

export * from "./generated/calendry/solver/v1/constraints.js";
export * from "./generated/calendry/solver/v1/model.js";
export * from "./generated/calendry/solver/v1/service.js";

/**
 * ts-proto emits its helper types into every generated file, so a bare
 * `export *` across all three leaves them ambiguous and TypeScript drops them
 * (TS2308). They are identical in each file, so re-exporting one copy
 * explicitly resolves the ambiguity — an explicit re-export takes precedence
 * over a star export.
 *
 * These are genuinely useful to consumers: `DeepPartial` is how you construct a
 * message without filling in every field.
 */
export type {
  DeepPartial,
  Exact,
  MessageFns,
} from "./generated/calendry/solver/v1/model.js";

export { protobufPackage } from "./generated/calendry/solver/v1/model.js";
